## 223. Numpy 배열 생성하기
인공지능 계산에는 행렬, 백터를 많이 사용한다. 이를 표현하기 위해 필요한 것이 Numpy의 배열이다.
Numpy의 배열은 Python의 리스트로부터 array()함수를 통해 쉽게 만들 수 있다.



In [1]:
# 리스트 2.33
import numpy as np

# 파이썬 리스트로부터 Numpy 배열을 만든다.
a = np.array([0,1,2,3,4,5])  
print(a)
print(type(a))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# 리스트 2.34
import numpy as np

# 2중 리스트로부터 Numpy의 2차원 배열을 만든다.
b = np.array([[0,1,2],[3,4,5]])
print(b)
print(type(b))

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>


In [21]:
# 리스트 2.35
import numpy as np

# 3중 리스트로부터 Numpy의 3차원 배열을 만든다.
c = np.array([[[0,1,2],
               [3,4,5]], 
              
              [[5,4,3],
               [2,1,0]]])
print(c)
print(type(c))

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]
<class 'numpy.ndarray'>


## 함수를 사용하여 Numpy배열 만들기
zeros()  -> 요소 수가 전부 0인 배열 <br>
ones()   -> 요소 수가 전부 1인 배열 <br>
arange()-> 0부터 인수 이전까지의 정수가 차례대로 나열된 배열

In [5]:
# 리스트 2.36
import numpy as np

# 0이 8개 저장된 배열
d = np.zeros(8)
print(d)
print(type(d))
print('')

# 1이 8개 저장된 배열
e = np.ones(8)
print(e)
print(type(e))
print('')

# 0부터 7까지 저장된 배열
f = np.arange(8)
print(f)
print(type(f))

[0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>

[1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>

[0 1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


## 224. 배열의 형태
데이터를 수집한 후 배열의 형태를 조사하는 과정은 매우 중요하다. <br>

컬럼의 개수, 데이터 행의 수, 데이터 타입 정보 등을 파악해야 후의 코딩에서 방향이 잡힐 수 있다.

In [8]:
# 리스트 2.37 shape()함수로 배열의 형태 얻기
import numpy as pd

a = np.array([[0,1,2],
              [3,4,5]])  # 2x3의 2차원 배열
print(a)
print('')
print(np.shape(a))

[[0 1 2]
 [3 4 5]]

(2, 3)


In [9]:
# 리스트 2.38_ len() 함수로 가장 바깥쪽 요소 수를 구한다.
import numpy as pd

a = np.array([[0,1,2],
              [3,4,5]])  # 2x3의 2차원 배열

print(a)
print('')
print(len(a))

[[0 1 2]
 [3 4 5]]

2


## 225. 배열의 연산

In [10]:
# 2.39_ 배열과 수치의 사칙 연산
import numpy as pd

a = np.array([[0,1,2],
              [3,4,5]])  # 2x3의 2차원 배열

print(a)
print()
print(a +3)
print()
print(a -3)
print()
print(a *3)
print()
print(a /3)

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[-3 -2 -1]
 [ 0  1  2]]

[[ 0  3  6]
 [ 9 12 15]]

[[0.         0.33333333 0.66666667]
 [1.         1.33333333 1.66666667]]


In [12]:
# 2.40_ 배열끼리의 사칙연산
import numpy as pd

a = np.array([[1,1,2],
              [3,4,5]])  # 2x3의 2차원 배열

b = np.array([[5,4,3],
              [2,1,8]])  # 2x3의 2차원 배열

print(a)
print()
print(b)
print()
print(a + b)
print()
print(a - b)
print()
print(a * b)
print()
print(a / b)

[[1 1 2]
 [3 4 5]]

[[5 4 3]
 [2 1 8]]

[[ 6  5  5]
 [ 5  5 13]]

[[-4 -3 -1]
 [ 1  3 -3]]

[[ 5  4  6]
 [ 6  4 40]]

[[0.2        0.25       0.66666667]
 [1.5        4.         0.625     ]]


## 226_ 요소로의 접근 <br>
배열의 각 요소로의 접근은 리스트의 경우와 마찬가지로 인덱싱을 통해 가능하다.

In [13]:
# 리스트2.41 인덱스를 지정하고, 배열의 요소로 접근한다.
import numpy as pd

a = np.array([1,2,3,4,5])
print(a[3]) # 3 인덱스를 지정

4


In [15]:
# 리스트2.42_ 인덱스를 지정해서 배열의 요소를 바꾼다.
import numpy as pd

a = np.array([1,2,3,4,5])
print(a[3]) # 3 인덱스를 지정
print()

a[3] = 9 # 4번째 자리 요소 9로 바꾸기
print(a[3])
print(a)

4

9
[1 2 3 9 5]


In [18]:
# 리스트2.43_ 2차원 배열의 요소로 접근하기
import numpy as pd

a = np.array([[1,1,2],
              [3,4,5]])  # 2x3의 2차원 배열

print(a[1,2])  # a[행, 열]  -> a[1][2]와 같다.

5


In [19]:
# 리스트2.44_ 2차원 배열의 요소 바꾸기
import numpy as pd

a = np.array([[1,1,2],
              [3,4,5]])  # 2x3의 2차원 배열

print(a[1,2])
a[1,2] = 9 # a의 1행 2열에 있는 요소를 9로 바꾸기

print(a[1,2])
print(a)

5
9
[[1 1 2]
 [3 4 9]]


In [24]:
# Extra_ 3차원 배열의 요소 바꾸기
import numpy as np

# 3중 리스트로부터 Numpy의 3차원 배열을 만든다.
c = np.array([[[0,1,2],
               [3,4,5]], 
              
              [[5,4,3],
               [2,1,0]]])

print(c[1,1,0])

c[1,1,0] = 9  # 1차원 1행 0열 요소를 9로 바꾸기

print(c[1,1,0])
print(c)

2
9
[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [9 1 0]]]


In [25]:
# 리스트2.45 행이나 열에 접근하기
import numpy as pd

a = np.array([[1,1,2],
              [3,4,5]])  # 2x3의 2차원 배열

print(a[1, :]) # a에서 인덱스가 1인 행을 추출하기
print()

a[:, 1] = np.array([9, 9]) # a에서 인덱스가 1인 열을 9로 바꾸기
print(a)

[3 4 5]

[[1 9 2]
 [3 9 5]]


# 함수와 배열

함수의 인수나 return값으로 Numpy 배열을 사용할 수 있다.

In [26]:
# 리스트2.46 함수의 인수, 반환값으로서의 배열
import numpy as pd

def my_func(x) :
    y = x * 2 + 1
    return y

a = np.array([[1,1,2],
              [3,4,5]])  # 2x3의 2차원 배열

b = my_func(a)  # 위에서 만든 함수 안에 array 2차원 배열 넣기

# 함수에 배열을 넣으면, 반환값을 배열을 받는다.

print(b)
print(type(b))

[[ 3  3  5]
 [ 7  9 11]]
<class 'numpy.ndarray'>


In [27]:
# 리스트 2.47_ Numpy가 가진 여러 가지 함수
import numpy as pd

a = np.array([[1,1,2],
              [3,4,5]])  # 2x3의 2차원 배열

print('합계', np.sum(a))
print('평균', np.average(a))
print('최댓값', np.max(a))
print('최솟값', np.min(a))

합계 16
평균 2.6666666666666665
최댓값 5
최솟값 1


## 229. 연습

Numpy의 2차원 배열을 두 개 기술하고, 서로의 합, 차, 곱을 구합시다.

In [29]:
import numpy as pd

a = np.array([[4,1,2],
              [3,0,5]])  # 2x3의 2차원 배열

b = np.array([[6,4,8],
              [3,2,1]])  # 2x3의 2차원 배열

print(a+b)
print()
print(a-b)
print()
print(a*b)

[[10  5 10]
 [ 6  2  6]]

[[-2 -3 -6]
 [ 0 -2  4]]

[[24  4 16]
 [ 9  0  5]]
