# 4.1 스칼라 벡터 행렬 텐서

## 411_스칼라

## 413_벡터
스칼라를 직선상에 나열한 것

In [1]:
# 리스트 4.2_Numpy의 1차원 배열로 나타낸다
import numpy as np

a = np.array([1,2,3]) # 1차원 배열로 벡터를 나타낸다.
print(a)

[1 2 3]


## 415_행렬

행렬은 스칼라를 격자 형태로 나열한 것

In [1]:
# 리스트 4.3_행렬을 Numpy의 2차원 배열로 나타낸다.
import numpy as np

a = np.array([[1,2,3],
             [4,5,6]]) # 2x3의 행렬
print(a)

[[1 2 3]
 [4 5 6]]


## 417_텐서
텐서는 스칼라를 여러 개의 차원으로 나열한 것
스칼라, 벡터, 행렬을 포함한다.

In [2]:
# 리스트 4.4_3층의 텐서를 Numpy의 배열로 나타낸다.
import numpy as np

a = np.array([[[0,1,2,3],
              [2,3,4,5],
              [4,5,6,7]],
             
             [[1,2,3,4],
             [3,4,5,6],
             [5,6,7,8]]]) # (2, 3, 4)-> (2차원 3행 4열)의 3차원 텐서
print(a)

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


# 4.2_벡터의 내적과 놈

## 421_내적
벡터끼리 곱의 한 종류

각 요소끼리 곱한 값을 총합

제한: 두 개의 벡터의 요소 수가 같아야 한다.

#### dot() 
함수로 간단하게 구할 수 있다.

#### sum()함수
를 이용해서 각 요소의 곱의 총합으로도 구할 수 있다.

#### 두 개 데이터의 상관관계를 구할 때 등에 사용


In [3]:
# 리스트 4.6_벡터의 내적을 계산한다.
import numpy as np

a = np.array([1,2,3])
b = np.array([3,2,1])

print('-------dot함수-------')
print(np.dot(a,b))
print()
print('-------sum함수-------')
print(sum(a*b))

-------dot함수-------
10

-------sum함수-------
10


## 423_놈
벡터의 '크기'를 나타내는 양

#### L2놈 np.linalg.norm() --> 디폴트가 L2인 함수
벡터의 각 요소를 제곱합하여 제곱근을 구함

#### L1놈 np.linalg.norm(,1) --> 1을 줘서 L1놈 구함 
벡터의 각 요소의 절댓값을 더해서 계산
<br>
<br>
#### 놈은 인공지능에서 정칙화에 쓰인다.
정칙화란 필요 이상으로 네트워크 학습이 진행되는 것을 파라미터로 조절해서 예방하는 것


##### linalg는 Linear Algebra라는 선형 대수학의 준말인듯

In [4]:
# 리스트 4.7_linalg.norm()함수를 사용해 놈을 계산한다.
import numpy as np

a = np.array([1, 1, -1, -1])

print('-------L2놈-------')
print(np.linalg.norm(a))
print()
print('-------L1놈-------')
print(np.linalg.norm(a,1))

-------L2놈-------
2.0

-------L1놈-------
4.0


# 4.3_ 행렬곱 vs 요소별 곱(아다마르 곱)

행렬곱은 dot() 함수를 사용한다.

In [5]:
# 리스트 4.10_ Numpy를 사용해서 행렬곱을 계산한다.
import numpy as np

a = np.array([[1,2,3],
             [4,5,6]]) # 2x3의 행렬

b = np.array([[2,1],
             [2,1],
             [2,1]])

print(np.dot(a, b))

[[12  6]
 [30 15]]


In [6]:
# 리스트 4.11_ Numpy를 사용해 요소별 곱을 계산한다.
import numpy as np

a = np.array([[1,1,2,3],
              [2,3,4,5],
              [4,5,6,7]])

b = np.array([[1,4,6,2],
              [2,3,1,1],
              [8,6,6,9]])

print('-------요소별 곱하기-------')
print(a*b)
print()
print('-------요소별 나누기-------')
print(a/b)
print()
print('-------요소별 더하기-------')
print(a+b)
print()
print('-------요소별 빼기-------')
print(a-b)

-------요소별 곱하기-------
[[ 1  4 12  6]
 [ 4  9  4  5]
 [32 30 36 63]]

-------요소별 나누기-------
[[1.         0.25       0.33333333 1.5       ]
 [1.         1.         4.         5.        ]
 [0.5        0.83333333 1.         0.77777778]]

-------요소별 더하기-------
[[ 2  5  8  5]
 [ 4  6  5  6]
 [12 11 12 16]]

-------요소별 빼기-------
[[ 0 -3 -4  1]
 [ 0  0  3  4]
 [-4 -1  0 -2]]


# 4.4_전치
전치를 통해 행과 열을 뒤바꿀 수 있다.
배열명 뒤에 .T 를 붙이면 된다.

In [7]:
# 리스트 4.14_ 행렬을 전치한다.
import numpy as np

a = np.array([[1,2,3],
             [4,5,6]]) # 2x3의 행렬
print(a)
print()
print(a.T)  # 원본을 바꾸진 않는다.
print()
print(a)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3]
 [4 5 6]]


## 444_전치와 행렬곱의 구현
전치를 통해

앞 행렬의 열수와 뒤 행렬의 행수를 일치시켜

곱을 가능하게 할 수도 있다.

In [8]:
# 리스트 4.15_ 전치하고 나서 행렬곱을 실시한다.
import numpy as np

a = np.array([[1,2,3],
             [4,5,6]]) # 2x3의 행렬

b = np.array([[1,2,3],
             [4,5,6]]) # 2x3의 행렬

print(np.dot(a, b.T))

[[14 32]
 [32 77]]


# 4.5_ 행렬식과 역행렬

## 451_ 단위행렬
같은 크기의 행렬에 곱해도 곱하는 대상의 행렬을 변화시키지 않는 성질이 있다.

행과 열 수가 같은 정방행렬의 경우에만 가능하다.

#### eye()함수

In [9]:
# 리스트 4.18 eye()함수를 사용해 단위행렬을 만든다.
import numpy as np

print(np.eye(2))  # 2x2의 단위행렬
print()
print(np.eye(3))  # 2x2의 단위행렬
print()
print(np.eye(4))  # 2x2의 단위행렬

[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 453_ 역행렬
곱하면 단위 행렬이 되는 행렬

## 454_ 행렬식
역행렬이 존재하지 않는 경우가 있다.

행렬식 = 0 인 경우 역행렬은 존재하지 않는다.

#### linalg.det() 함수

In [10]:
# 리스트 4.19 linalg.det() 함수를 사용해 행렬식을 구한다.
import numpy as np

a = np.array([[1,2],
             [3,4]]) # 2x3의 행렬

print(np.linalg.det(a)) # 행렬식이 0이 되지 않는 경우

b = np.array([[1,2],
             [0,0]]) # 2x3의 행렬
print(np.linalg.det(b)) # 행렬식이 0이 되는 경우

-2.0000000000000004
0.0


## 456_ 역행렬의 구현
linalg.det() = 0 이 아닌 경우
#### linalg.inv() 함수
inv는 inverse의 약자

##### 역행렬은 인공지능에서 변수끼리의 상관관계를 알아보는 회귀분석에 활용된다.

In [11]:
# 리스트 4.20 linalg.inv() 함수를 사용해 역행렬을 구한다.
import numpy as np

a = np.array([[1,2],
             [3,4]]) # 2x3의 행렬

print(np.linalg.inv(a)) # 행렬식이 0이 되지 않는 경우

[[-2.   1. ]
 [ 1.5 -0.5]]


# 4.6_ 